# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Completed - the list of completed transactions',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=1)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Orders - list of orders for a single product',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=b'', help_text=b'Name of the product.', max_length=64)),
                ('Manufacturer', models.CharField(default=b'', help_text=b'Manufacturer of the product.', max_length=64)),
                ('Description', models.TextField(default=b'', help_text=b'Description of the product.')),
                ('Price', models.FloatField(default=1, help_text=b'Price per item.')),
                ('Number', models.IntegerField(default=0, help_text=b'In Stock')),
                ('Image', models.ImageField(default=b'image/product/default.jpg', upload_to=b'image/product/')),
                ('URL', models.URLField(help_text=b'Address of the manufacturer.', null=True)),
                ('AddedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('StocksDate', models.DateTimeField(blank=True, help_text=b'When was the last time was available', null=True)),
            ],
            options={
                'verbose_name_plural': 'Products - list of all products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Categories - list of all category products',
            },
        ),
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64)),
                ('Address', models.CharField(help_text=b'Street, house number, postcode.', max_length=128)),
                ('City', models.CharField(max_length=64)),
                ('Country', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Delivery addresses',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Shopping List - a list of purchases for a single user',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('basket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Basket')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Bought - list of orders transferred to realization',
            },
            bases=('shop.basket',),
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('shoppinglist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.ShoppingList')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('CompletedList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CompletedList')),
            ],
            bases=('shop.shoppinglist',),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Basket'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='CompletedList',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.CompletedList'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ShoppingList',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.ShoppingList'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='UserAccounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.UserAccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='Container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Basket'),
        ),
        migrations.AddField(
            model_name='order',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='bought',
            name='ShippingInformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShippingInformation'),
        ),
        migrations.AddField(
            model_name='bought',
            name='ShoppingList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShoppingList'),
        ),
    ]
