# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.PositiveIntegerField(default=1, help_text=b'Price per item.'),
        ),
    ]
