# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160111_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Categorty',
            new_name='Category',
        ),
    ]
