# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160226_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Number',
            field=models.PositiveIntegerField(default=0, help_text=b'In Stock'),
        ),
    ]
