# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 23:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160112_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 11, 23, 10, 41, 515000, tzinfo=utc)),
        ),
    ]
