# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 23:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20160112_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Manufacturer',
            field=models.CharField(default=b'', help_text=b'Manufacturer of the product.', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='URL',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 11, 23, 45, 5, 490000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(default=b'', help_text=b'Description of the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(default=b'', help_text=b'Name of the product.', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(default=1, help_text=b'Price per item.'),
        ),
    ]
