# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20160112_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 0, 37, 14, 905000, tzinfo=utc)),
        ),
    ]
