# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20160112_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 0, 39, 34, 290000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Number',
            field=models.IntegerField(default=0, help_text=b'In Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='StocksDate',
            field=models.DateTimeField(blank=True, help_text=b'When was the last time was available', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='URL',
            field=models.URLField(help_text=b'Address of the manufacturer.', null=True),
        ),
    ]
