# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20160112_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 0, 46, 1, 409000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 12, 0, 46, 1, 408000, tzinfo=utc)),
        ),
    ]
