# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160112_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='Orders',
            field=models.ManyToManyField(blank=True, to='shop.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='AddedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
