# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160112_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderToBasketRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='Orders',
        ),
        migrations.AddField(
            model_name='ordertobasketrelation',
            name='Basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Basket'),
        ),
        migrations.AddField(
            model_name='ordertobasketrelation',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
