# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_auto_20160112_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderToAnOrderRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.AnOrder')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64)),
                ('CompanyName', models.CharField(max_length=64, null=True)),
                ('Address', models.CharField(help_text=b'Street, house number, postcode.', max_length=128)),
                ('City', models.CharField(max_length=64)),
                ('Country', models.CharField(max_length=64)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
