# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_anorder_ordertoanorderrelation_shippinginformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
