# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20160112_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='anorder',
            name='ShippingInformation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.ShippingInformation'),
            preserve_default=False,
        ),
    ]
