# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_anorder_shippinginformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='CompanyName',
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.UserAccount'),
        ),
    ]
