# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20160219_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginformation',
            old_name='User',
            new_name='UserAccounts',
        ),
    ]
