# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20160219_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('basket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Basket')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ShippingInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShippingInformation')),
            ],
            bases=('shop.basket',),
        ),
        migrations.CreateModel(
            name='CompletedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='anorder',
            name='ShippingInformation',
        ),
        migrations.RemoveField(
            model_name='anorder',
            name='User',
        ),
        migrations.RemoveField(
            model_name='ordertoanorderrelation',
            name='AnOrder',
        ),
        migrations.RemoveField(
            model_name='ordertoanorderrelation',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='ordertobasketrelation',
            name='Basket',
        ),
        migrations.RemoveField(
            model_name='ordertobasketrelation',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='User',
        ),
        migrations.AddField(
            model_name='order',
            name='Container',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Basket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Basket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Basket'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('shoppinglist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.ShoppingList')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('CompletedList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CompletedList')),
            ],
            bases=('shop.shoppinglist',),
        ),
        migrations.DeleteModel(
            name='AnOrder',
        ),
        migrations.DeleteModel(
            name='OrderToAnOrderRelation',
        ),
        migrations.DeleteModel(
            name='OrderToBasketRelation',
        ),
        migrations.AddField(
            model_name='bought',
            name='ShoppingList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShoppingList'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='CompletedList',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.CompletedList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ShoppingList',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.ShoppingList'),
            preserve_default=False,
        ),
    ]
